/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Victor Neves
 */
public class Terms extends javax.swing.JFrame {

    /**
     * Creates new form Terms
     */
    public Terms() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVolver = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SysTurno v1.0.0 Alpha");
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVolver.setBackground(new java.awt.Color(0, 0, 51));
        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("<< Volver");
        jButtonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVolverMouseClicked(evt);
            }
        });
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Términos y Condiciones Generales");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 330, 30));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\tSysTurno es una aplicación de uso masivo creada por la compañía “Los de Melo”, siendo \npropiedad intelectual de la misma y solamente esta podrá disponer de su uso, mantenimiento y contratación.\n\tEsta aplicación es una herramienta para la optimización de los servicios brindados en \nfarmacias públicas y privadas de instituciones de salud.\n\tAl  descargar, instalar, acceder, usar, obtener o brindar información desde y hacia esta \nAplicación, se considerará que los usuarios han leído y aceptado estos Términos y Condiciones \n(incluyendo nuestra Política de protección de datos personales basada en la Ley 18331 de la República \nOriental del Uruguay), que se incorpora al presente documento en virtud de esta referencia.\n(Ref.: https://www.impo.com.uy/bases/leyes/18331-2008/29)\n\tLos contenidos de SysTurno tales como textos, cuadros, datos, imágenes, iconos, logos así \ncomo cualquier otro contenido son propiedad de la compañía.\n\tLos usuarios liberarán a la compañía de toda responsabilidad y exonerarán de todo reclamo, \ndemanda responsabilidad civil, causa legal o daños y perjuicios que surjan como consecuencia del uso que \ndichos usuarios hagan de la Aplicación incluyendo, entre otros, la información y contenido suministrada o \nvertida por la misma.\n\tLa compañía se reserva el derecho de en cualquier momento y sin previo aviso realizar \nmodificaciones simples o sustanciales a la aplicación, así como suspenderla temporal o definitivamente.\nLos usuarios deben suspender el uso de esta Aplicación inmediatamente si no están de acuerdo o no\naceptan todos estos Términos y Condiciones. La empresa contratante se reserva el derecho de eliminar\no prohibir a cualquier usuario la utilización de esta Aplicación a su sola discreción.\n\n“Los De Melo”");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 600, 360));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVolverMouseClicked
        // TODO add your handling code here:
        MenuNuevo menu = new MenuNuevo();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}