-- MySQL Script generated by MySQL Workbench
-- Tue Mar  5 17:55:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema systurno
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema systurno
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `systurno` DEFAULT CHARACTER SET utf8 ;
USE `systurno` ;

-- -----------------------------------------------------
-- Table `systurno`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systurno`.`Usuarios` (
  `CI` INT(8) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellido` VARCHAR(30) NOT NULL,
  `Telefono` VARCHAR(12) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `sal` VARCHAR(65) NOT NULL,
  `hash` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`CI`),
  UNIQUE INDEX `CI_UNIQUE` (`CI` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systurno`.`Doctores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systurno`.`Doctores` (
  `CI` INT(8) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellido` VARCHAR(30) NOT NULL,
  `Telefono` VARCHAR(12) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `sal` VARCHAR(65) NOT NULL,
  `hash` VARCHAR(32) NOT NULL,
  `Especialidad` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`CI`),
  UNIQUE INDEX `CI_UNIQUE` (`CI` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systurno`.`medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systurno`.`medicamentos` (
  `ID` INT NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `laboratorio` VARCHAR(30) NOT NULL,
  `principio` VARCHAR(50) NOT NULL,
  `presentacion` VARCHAR(30) NOT NULL,
  `controlado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systurno`.`recetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systurno`.`recetas` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systurno`.`turnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systurno`.`turnos` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `fechahora` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systurno`.`sesiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systurno`.`sesiones` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `fechahora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` ENUM('activa', 'cerrarda') NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systurno`.`inicia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systurno`.`inicia` (
  `Ci_usuario` INT(8) NOT NULL,
  `ID_sesion` INT NOT NULL,
  PRIMARY KEY (`ID_sesion`),
  INDEX `fk_inicia_Usuarios1_idx` (`Ci_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_inicia_sesiones1`
    FOREIGN KEY (`ID_sesion`)
    REFERENCES `systurno`.`sesiones` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inicia_Usuarios1`
    FOREIGN KEY (`Ci_usuario`)
    REFERENCES `systurno`.`Usuarios` (`CI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systurno`.`genera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systurno`.`genera` (
  `CI_usuario` INT(8) NOT NULL,
  `ID_turno` INT NOT NULL,
  PRIMARY KEY (`ID_turno`),
  INDEX `fk_CI_usuario_turno_idx` (`CI_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_CI_usuario_turno`
    FOREIGN KEY (`CI_usuario`)
    REFERENCES `systurno`.`Usuarios` (`CI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ID_turno`
    FOREIGN KEY (`ID_turno`)
    REFERENCES `systurno`.`turnos` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systurno`.`asociado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systurno`.`asociado` (
  `turnos_ID` INT NOT NULL,
  `recetas_ID` INT NOT NULL,
  PRIMARY KEY (`recetas_ID`),
  INDEX `fk_asociado_turnos1_idx` (`turnos_ID` ASC) VISIBLE,
  INDEX `fk_asociado_recetas1_idx` (`recetas_ID` ASC) VISIBLE,
  CONSTRAINT `fk_asociado_turnos1`
    FOREIGN KEY (`turnos_ID`)
    REFERENCES `systurno`.`turnos` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asociado_recetas1`
    FOREIGN KEY (`recetas_ID`)
    REFERENCES `systurno`.`recetas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systurno`.`recibe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systurno`.`recibe` (
  `Usuarios_CI` INT(8) NOT NULL,
  `recetas_ID` INT NOT NULL,
  PRIMARY KEY (`recetas_ID`),
  INDEX `fk_recibe_Usuarios1_idx` (`Usuarios_CI` ASC) VISIBLE,
  INDEX `fk_recibe_recetas1_idx` (`recetas_ID` ASC) VISIBLE,
  CONSTRAINT `fk_recibe_Usuarios1`
    FOREIGN KEY (`Usuarios_CI`)
    REFERENCES `systurno`.`Usuarios` (`CI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recibe_recetas1`
    FOREIGN KEY (`recetas_ID`)
    REFERENCES `systurno`.`recetas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systurno`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systurno`.`entrega` (
  `Doctores_CI` INT(8) NOT NULL,
  `recetas_ID` INT NOT NULL,
  PRIMARY KEY (`recetas_ID`),
  INDEX `fk_entrega_Doctores1_idx` (`Doctores_CI` ASC) VISIBLE,
  INDEX `fk_entrega_recetas1_idx` (`recetas_ID` ASC) VISIBLE,
  CONSTRAINT `fk_entrega_Doctores1`
    FOREIGN KEY (`Doctores_CI`)
    REFERENCES `systurno`.`Doctores` (`CI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrega_recetas1`
    FOREIGN KEY (`recetas_ID`)
    REFERENCES `systurno`.`recetas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systurno`.`contiene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systurno`.`contiene` (
  `medicamentos_ID` INT NOT NULL,
  `recetas_ID` INT NOT NULL,
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_contiene_medicamentos1_idx` (`medicamentos_ID` ASC) VISIBLE,
  INDEX `fk_contiene_recetas1_idx` (`recetas_ID` ASC) VISIBLE,
  CONSTRAINT `fk_contiene_medicamentos1`
    FOREIGN KEY (`medicamentos_ID`)
    REFERENCES `systurno`.`medicamentos` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contiene_recetas1`
    FOREIGN KEY (`recetas_ID`)
    REFERENCES `systurno`.`recetas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
