/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor Neves
 */
public class Cancelar extends javax.swing.JFrame {
    CapaLogica acciones = new CapaLogica();
    MenuNuevo vt_menu;
    DatosSesion infoSesion;
    String[] datosTurno;

    /**
     * Creates new form Terms
     */
    public Cancelar(MenuNuevo menu, DatosSesion sesion) {
        initComponents();
        this.setLocationRelativeTo(null);
        vt_menu = menu;
        infoSesion = sesion;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_medicamentos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ftf_numTurno = new javax.swing.JFormattedTextField();
        ftf_fecha = new javax.swing.JFormattedTextField();
        ftf_hora = new javax.swing.JFormattedTextField();
        bt_cancelarTurno = new javax.swing.JButton();
        bt_volver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SysTurno v1.0.0 Alpha");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_medicamentos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbl_medicamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Disponibilidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_medicamentos.setAutoscrolls(false);
        tbl_medicamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tbl_medicamentos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 530, 110));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hora:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 60, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Número:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 70, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 60, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cancelación de Turno");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 270, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Medicamentos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 110, 40));

        ftf_numTurno.setEditable(false);
        ftf_numTurno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ftf_numTurno.setText("25");
        ftf_numTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftf_numTurnoActionPerformed(evt);
            }
        });
        getContentPane().add(ftf_numTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 80, -1));

        ftf_fecha.setEditable(false);
        ftf_fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        ftf_fecha.setText("25/03/2019");
        getContentPane().add(ftf_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 80, -1));

        ftf_hora.setEditable(false);
        ftf_hora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        ftf_hora.setText("14:30");
        getContentPane().add(ftf_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 80, -1));

        bt_cancelarTurno.setBackground(new java.awt.Color(0, 0, 51));
        bt_cancelarTurno.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bt_cancelarTurno.setForeground(new java.awt.Color(255, 255, 255));
        bt_cancelarTurno.setText("Cancelar Turno");
        bt_cancelarTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cancelarTurnoMouseClicked(evt);
            }
        });
        bt_cancelarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarTurnoActionPerformed(evt);
            }
        });
        getContentPane().add(bt_cancelarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        bt_volver.setBackground(new java.awt.Color(0, 0, 51));
        bt_volver.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bt_volver.setForeground(new java.awt.Color(255, 255, 255));
        bt_volver.setText("<< Volver");
        bt_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_volverMouseClicked(evt);
            }
        });
        bt_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_volverActionPerformed(evt);
            }
        });
        getContentPane().add(bt_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Condiciones Generales:\n\n- Solo se podrá retirar medicamentos presentando cédula de identidad original del paciente.\n- Los medicamentos de venta bajo receta solo se entregarán contra presentación de la misma.");
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 530, 110));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cancelarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_cancelarTurnoActionPerformed

    private void bt_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_volverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_volverActionPerformed

    private void ftf_numTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftf_numTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftf_numTurnoActionPerformed

    private void bt_cancelarTurnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cancelarTurnoMouseClicked
        // TODO add your handling code here:
        DialogoOkCancel dlg = new DialogoOkCancel(this, true);
        dlg.setVisible(true);
        if(dlg.getReturnStatus()==1){
            MenuNuevo menu = new MenuNuevo();
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_bt_cancelarTurnoMouseClicked

    private void bt_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_volverMouseClicked
        // TODO add your handling code here:o
        vt_menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_volverMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        acciones.mostrarMedicamentosRecetados(infoSesion, tbl_medicamentos);
        acciones.verDatosTurnoActual(infoSesion, ftf_numTurno, ftf_fecha, ftf_hora, datosTurno);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelarTurno;
    private javax.swing.JButton bt_volver;
    private javax.swing.JFormattedTextField ftf_fecha;
    private javax.swing.JFormattedTextField ftf_hora;
    private javax.swing.JFormattedTextField ftf_numTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tbl_medicamentos;
    // End of variables declaration//GEN-END:variables
}
