/*
 * Copyright (C) 2019 Sebastian
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ventanas;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastian
 */
public class ConfirmaReserva extends javax.swing.JDialog {
    
    boolean opcion=false;
    static DefaultTableModel datos;
    static String msgTurno;

    /**
     * Creates new form ConfirmaReserva
     */
    
    public ConfirmaReserva( java.awt.Frame parent, 
                            boolean modal,
                            String msgTurno,
                            DefaultTableModel listaMed) {
        super(parent, modal);
        initComponents();
        this.datos = listaMed;
        this.msgTurno = msgTurno;
        this.setLocationRelativeTo(null);
        lbl_confirma.setText(msgTurno);
        tbl_listaMed.setModel(datos);
//tf_medicamentos.setText(listaMed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_confirma = new javax.swing.JButton();
        bt_cancela = new javax.swing.JButton();
        lbl_confirma = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_listaMed = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_confirma.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bt_confirma.setText("Confirmar");
        bt_confirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_confirmaMouseClicked(evt);
            }
        });
        getContentPane().add(bt_confirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 130, 20));

        bt_cancela.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bt_cancela.setText("Cancelar");
        bt_cancela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cancelaMouseClicked(evt);
            }
        });
        bt_cancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelaActionPerformed(evt);
            }
        });
        getContentPane().add(bt_cancela, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 110, 20));

        lbl_confirma.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_confirma.setForeground(new java.awt.Color(255, 255, 255));
        lbl_confirma.setText("Confirma el turno?");
        getContentPane().add(lbl_confirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 460, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Medicamentos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        tbl_listaMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_listaMed);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAzul.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_cancelaActionPerformed

    private void bt_confirmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_confirmaMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        opcion = true;
        
    }//GEN-LAST:event_bt_confirmaMouseClicked

    private void bt_cancelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cancelaMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        opcion = false;
    }//GEN-LAST:event_bt_cancelaMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //lbl_confirma.setText(msgTurno);
        //tbl_listaMed.setModel(datos);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfirmaReserva dialog = new ConfirmaReserva(new javax.swing.JFrame(), true,msgTurno,datos);
                
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancela;
    private javax.swing.JButton bt_confirma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_confirma;
    private javax.swing.JTable tbl_listaMed;
    // End of variables declaration//GEN-END:variables
}
